language: python
dist: trusty
sudo: required
python:
    - "2.7"
    - "pypy"
install:
    - sudo apt-get update -q
    - sudo apt-get install intltool desktop-file-utils
    - pip install coverage minimock
    - python tools/localdepends.py
script:
    - make releasetest
